### ISSUE TITLE
How to use configs

### ISSUE THREAD

**Issue by judory** [hpanwar08/detectron2#11]
I think "--num-gpus 8" config is not working with train_net_dla.py when I tryed to training from scratch.
How can I set the config?

**Comment by hpanwar08** [comment]
`train_net_dla.py` runs as module using only 1 gpu and does not take command line arguments. If you want use multiple gpus then you need to modify `train_net_dla.py`. Have a look at `train_net.py` and `detectron2.engine.launch.py`

**Comment by oym050922021** [comment]
hi,there is not train_net_dla.py in the directory called tools.please why?

**Comment by hpanwar08** [comment]
https://github.com/hpanwar08/detectron2/blob/master/tools/train_net_dla.py

**Comment by oym050922021** [comment]
hi,
  thank you very much!













在 2020-05-05 16:02:05，"Himanshu" <notifications@github.com> 写道：

https://github.com/hpanwar08/detectron2/blob/master/tools/train_net_dla.py
