### ISSUE TITLE
no VERSION error while following the readme instruction

### ISSUE THREAD

**Issue by jocelynguo** [hpanwar08/detectron2#12]
Hi, when I got the error by calling
```python demo/demo.py --config-file configs/DLA_mask_rcnn_X_101_32x8d_FPN_3x.yaml --input “/home/jupyter/layout/detectron2/input.jpg” --output “/home/jupyter/layout/” --confidence-threshold 0.5 --opts MODEL.WEIGHTS /home/jupyter/layout/detectron2/model_final_trimmed.pth MODEL.DEVICE cpu```
Here is the error, not sure why the .yaml doesn't have VERSION. Thank you
```
WARNING [03/26 04:43:12 d2.config.compat]: Config 'configs/DLA_mask_rcnn_X_101_32x8d_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "demo/demo.py", line 76, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/jupyter/layout/detectron2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 168, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/opt/conda/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 103, in load
    checkpoint = self._load_file(path)
  File "/opt/conda/lib/python3.7/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 42, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "/opt/conda/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 189, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 16489904 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f545aa70193 in /opt/conda/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x186b6af (0x7f545c72e6af in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: THStorage_free + 0x17 (0x7f545cef6cb7 in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x55d23d (0x7f54a377223d in /opt/conda/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: __libc_start_main + 0xf1 (0x7f54c6f032e1 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted
```

**Comment by hpanwar08** [comment]
yaml version is just a warning, it should not affect the processing.
From the log, error seems to coming while loading the model. Can you verify if model file exists and is valid.

**Comment by jocelynguo** [comment]
Sorry, it was my problem. One more question: Where is the folder that you save the PubLayNet dataset? Thank you

**Comment by hpanwar08** [comment]
Publaynet dataset is huge, it is not saved on github.
refer this https://github.com/ibm-aur-nlp/PubLayNet to get the data.

**Comment by jocelynguo** [comment]
I use the model to predict the bounding box of the article, and I found a common issue that few closer boxes may have overlap area. I know we can set a IoU threshold to eliminate or correct the boundary, but somehow it's not robust. Do you have any recommendation to solve this issue?

**Comment by hpanwar08** [comment]
Are you predicting on publaynet data?

As you already mentioned, changing the threshold could eliminate some of the overlap, but that may also introduce some other effects. Lowering the threshold could increase the overlap while increasing it could miss out some of the location. Threshold could be determined empirically based on your data.

Another way is to train the model to converge it further.
Try to use resnext101 if you are not already using it.
