### ISSUE TITLE
mask_rcnn_R_50_FPN_3x.yaml

### ISSUE THREAD

**Issue by deepseek** [hpanwar08/detectron2#14]
@hpanwar08 

Why did you train using `x101 fpn`, have you tested `mask_rcnn_R_50_FPN_3x.yaml`?

**Comment by hpanwar08** [comment]
As per the Publaynet paper, `x101` and `R101` gave good results.
I did not try `mask_rcnn_R_50_FPN_3x.yaml` although I tried `faster_rcnn_R_50_FPN_3x.yaml` which was not as good as `x101` in terms of bounding box, but it is much smaller and faster.

**Comment by deepseek** [comment]
Thanks

**Comment by deepseek** [comment]
@hpanwar08 Also upload the `DLA_mask_rcnn_R_50_FPN_3x.yaml` files that you used for training and inferencing.

**Comment by deepseek** [comment]
Thanks, you are amazing! @hpanwar08
