### ISSUE TITLE
Trimming Definition?

### ISSUE THREAD

**Issue by unded666** [hpanwar08/detectron2#19]
Hi there. 

Thanks so much for releasing Detectron2. 

I'm trying to benchmark our own extensions from the detectron2 model, and as a part of
the process I need to define what is going on with the model trimming. Can you please explain 
how the model is trimmed (and if possible where in the api you would do this)?

A pointer to documentation I have missed would be perfectly fine as well.

Thanks.

**Comment by hpanwar08** [comment]
Hi,
Thanks. 
Detectron2 saves optimizer, iteration, scheduler in addition to the actual model weights in a single file. It increases the model (.pth) file size. Trimmed model contains only the weights part of the .pth file.

refer https://github.com/hpanwar08/detectron2/issues/10

**Comment by unded666** [comment]
Fantastic, that clears everything up nice and cleanly.
