### ISSUE TITLE
Has anyone trained a model on more general pdf documents?

### ISSUE THREAD

**Issue by sybrenh** [hpanwar08/detectron2#23]
## Does a more general model already exist?

Hi, I'm planning to apply Detectron2 on more general pdf documents from all sorts of companies. Is there a feature or model already present or is my best option to start fine tuning the existing model by making my own test dataset? Thanks in advance

**Comment by hpanwar08** [comment]
If you data and labels are similar to the Publaynet dataset then this repo model would be decent enough. But if the data is different or you want to detect more categories then labeling new data and finetuning is the way to go.

**Comment by sybrenh** [comment]
Alright, I will finetune it further, thank you for your response!
