### ISSUE TITLE
What is the process of finetuning in colab?

### ISSUE THREAD

**Issue by sybrenh** [hpanwar08/detectron2#24]
Hi, while I am trying to finetune the publaynet model in colab I keep running into errors. What would the process of this be? Should I start with this package or the normal detectron2 from facebookreserch? I have tried to manually add the publaynet model to my google drive but it does not seem to work that way. Some steps to achieve this would be of great help. 

Thanks in advance

**Comment by hpanwar08** [comment]
What are the errors you encounter? You should install the normal detectron2 then use the config file and model from this repo. Create a new config file for your finetuning with required classes, batch size etc. and set the model weights in the config as the model from this repo.

**Comment by sybrenh** [comment]
Thank you for your response! I figured out what the problem was, in google colab, make sure to use !wget to import a model. Adding it manually creates a corrupt file which generates countless of errors.

**Comment by GitOfRandom** [comment]
> Thank you for your response! I figured out what the problem was, in google colab, make sure to use !wget to import a model. Adding it manually creates a corrupt file which generates countless of errors.

It would be kind if you share your colab notebook. Thanks in advance.

**Comment by hpanwar08** [comment]
I don't have notebook handy right now. It would take some time to make one.
