### ISSUE TITLE
Are the models fine tune-able?

### ISSUE THREAD

**Issue by GitOfRandom** [hpanwar08/detectron2#25]
## ❓ How to Finetune these new models

1. Are the three models provided work in same way as pre-trained models?
2. How to finetune them?

It would be great if you can provide script for fine-tuning.

**Comment by hpanwar08** [comment]
All 3 models work the same way. 
You can use `train_net_dla.py` to finetune. Add `cfg.MODEL.WEIGHTS = "<path to dla trained model>"` in your `train_net_dla.py`

**Comment by theCodinCowboy** [comment]
Where is train_net_dla.py? What if I want to train a new model such as F-CNN? Better question I have is where is the actual train and test code located?
