### ISSUE TITLE
Any plan to train the Faster R-CNN model using PubLayNet data on Detectron2?

### ISSUE THREAD

**Issue by yfeng14** [hpanwar08/detectron2#26]
## 🚀 Feature
Thanks for providing the pretrained Mask R-CNN models! Just curious whether you have a plan to provide pretrained Faster R-CNN models as well? I believe it'll be helpful for fine tuning tasks where pixel-level annotation is not easy to get.

**Comment by hpanwar08** [comment]
Thank you for your interest, right now there is no plan for training faster rcnn but I will try to train atleast 1 models as and when there is bandwidth.
