### ISSUE TITLE
How to get region features for a bounding box specified by the user

### ISSUE THREAD

**Issue by mineshmathew** [hpanwar08/detectron2#28]
Thank you @hpanwar08  for providing with  detectron2 trained publaynet models.
I wanted help with using this model to extract region features of the objects (the layout elements detected) detected

**Comment by hpanwar08** [comment]
Hi, sorry for the delay in response. For region features you need to look into `proposal_generator`, `roi_heads` section of the model. I do not have a ready made script got this.
Did you get what you were looking for?

**Comment by mineshmathew** [comment]
Yes I was able to get the features.  The thread [here](https://github.com/facebookresearch/detectron2/issues/5) helped me.

**Comment by asadnorouzi** [comment]
@mineshmathew Did you match the extracted features with the predicted masks? What I'm trying to do is to get only the features of the masked regions obtained from the DefaultPredictor.

@hpanwar08 I'd appreciate it if you could shed some light on my question above. Thanks.
