### ISSUE TITLE
Training from scratch

### ISSUE THREAD

**Issue by theCodinCowboy** [hpanwar08/detectron2#29]
I want to train a model from scratch. It looks like the tools directory is where I should dive into. I have the PubLayNet data, but I refined the data I want to use, and don't want to use the pre-trained models or weights(All the labels are the same format). How would I go about training a fresh model? 

Thanks in advance.

**Comment by hpanwar08** [comment]
Training process should be same. You can use `train_net_dla.py` with minimal code changes (change line 132 to 144) or if you want to write your own then have a look at latest `train_net.py` in original detectron2.
