### ISSUE TITLE
How did you do training?

### ISSUE THREAD

**Issue by theCodinCowboy** [hpanwar08/detectron2#30]
I did the normal training from scratch with the LR at .0009 for 125k iterations like is shown in the config file for DLA_mask_rcnn_X_101_32x8d_FPN_3x.yaml. and am only getting a 77.22 AP score. This learning rate is the last one that IBM had used so confused as to what your training process looked like, and if you changed learning rates when getting a total of 190K iterations that it looks like you did. 

So the question is, what exactly did your training run look like on the DLA_mask_rcnn_X_101_32x8d_FPN_3x.yaml to get a ~90 AP score.

Thanks!

**Comment by hpanwar08** [comment]
Try to increase the learning rate. The latest learning rate that I used is 0.0025 for training on the entire dataset.
