### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by rakshit-ce** [hpanwar08/detectron2#32]
Hi, I tried the `train_net_dla.py` script in the repo to finetune on custom data. Data is all fine, but I'm getting this error just before training starts: `RuntimeError: Not compiled with GPU support`. I double checked everything !! not able to figure out this issue ??

**Comment by rakshit-ce** [comment]
You mentioned that you used this same script to train on `publaynet` dataset. So it should work right ??

**Comment by hpanwar08** [comment]
Seems like a detectron2 issue. https://detectron2.readthedocs.io/tutorials/install.html#common-installation-issues
