### ISSUE TITLE
What Image size to use and do I need to normalize the images

### ISSUE THREAD

**Issue by mineshmathew** [hpanwar08/detectron2#33]
1. What size are the images resized to while training on document images. While testing do you suggest to use any specific sizes
2. Do I need to do any sort of normalization on the input images. I see that in case of object detection models in case of natural images, it is a common practice to normalize images using mean and SD computed from imagenet dataset

**Comment by hpanwar08** [comment]
1. You can check the image resizing parameters here https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py#L50 . Shorter side is resized to 800 and longer size is kept in proportion and not greater than 1333. Using the default sizes gives decent results for testing also.
2. Image normalization is done in the model itself, no need to do it externally. I have to used the same imagenet mean and std.
