### ISSUE TITLE
Yolo v4

### ISSUE THREAD

**Issue by seekingdeep** [hpanwar08/detectron2#34]
@hpanwar08 hi there,
1) have you tested yolo v4?
2) do you think yolov4 is suitable for detecting text?
3) are you available for freelancing?

**Comment by hpanwar08** [comment]
Hi @seekingdeep 
1. I haven't tried yolov4 but yolov3. Detectron2 is better on smaller object compared to yolov3. Although yolov3 is much faster
2. No idea for yolov4, but it would depend on the type of text you want to detect. You can have a look at http://arxiv.org/abs/2006.04305
3. I am a little tied up as of now

**Comment by seekingdeep** [comment]
thanks
