### ISSUE TITLE
How to set category id when fine tuning with an existing class

### ISSUE THREAD

**Issue by ninamanojlovic1** [hpanwar08/detectron2#38]
Hi,

I want to fine-tune the model with an existing class (table in my case). How should I set the category id of the new data? What should be its value, in a sense should it be the same as in the pre-trained model? 

Thanks in advance!

**Comment by rakshit-ce** [comment]
Yes

**Comment by hpanwar08** [comment]
If your data has only 1 class, then set number classes to 1 in config file

**Comment by ninamanojlovic1** [comment]
Thanks for the answers :) I did that part, I was more concerned about category_id from that class, in the sense should I set that to be 4, since in the publaynet table had category_id 4?

**Comment by hpanwar08** [comment]
Are you fine tuning on your custom data?

**Comment by ninamanojlovic1** [comment]
I am fine-tuning by adding additional data for tables (some financial dataset). So I am adding more images that are only labeled with tables. And since that class already exists in the pre-trained model I was wondering how to tell the model we are extending the existing class. So this is why I was wondering whether category_id in my new annotation file should be 4 because in the publaynet it was 4 for tables?

Thanks!

**Comment by hpanwar08** [comment]
Will your final model predict annotations for only tables or other classes like text title also? If its only table then it should not matter.

**Comment by ninamanojlovic1** [comment]
Tables are my main goal, so I guess my assumption about category_id is not correct. OK, thank you very much for your help
