### ISSUE TITLE
How to create Evaluation metrics for custom PDF dataset

### ISSUE THREAD

**Issue by Naveenkhasyap** [hpanwar08/detectron2#4]
Hi ,
I wanted to Know how to calculate the evaluation metrics for custom dataset which has only pdf, no xml as told by the PublayNet paper anyone tried this?

I ran this on my documents got the labels and their predictions but now I need to calculate the accuracy with ground truth but I don't have the labelled data so is there any way to calculate metrics for the results.

**Comment by hpanwar08** [comment]
To calculate the metrics you need the ground truth e.g annotated images. You can label some documents then calculate the metrics.

**Comment by Naveenkhasyap** [comment]
Hi @hpanwar08 , yes got it thanks
