### ISSUE TITLE
Fine-tuning: AttributeError: Cannot find field 'gt_masks' in DataLoader with COCO format

### ISSUE THREAD

**Issue by mbuet2ner** [hpanwar08/detectron2#40]
Unfortunately, I always run into an error when fine-tuning on my own dataset (in coco format).
The [detectron2 documentation](https://github.com/facebookresearch/detectron2/blob/master/docs/tutorials/datasets.md) on datasets was of no help either (maybe I overlooked something though).

After registering the data via `register_coco_instances` (as seen in `train_net_dla.py`) the following code
```
train data (train_data = DatasetCatalog.get("dla_train")
train data[0]
```
gives me:
```
{'file_name': 'cyber_train/public_imgs_sampled/file01.png',
 'height': 1754,
 'width': 1241,
 'image_id': 0,
 'annotations': [{'iscrowd': 0,
   'bbox': [78, 600, 977, 33],
   'category_id': 1,
   'segmentation': [[83, 606, 83, 633, 1050, 633, 1050, 606]],
   'bbox_mode': <BoxMode.XYWH_ABS: 1>}
...
```
which does look good to me telling from the [COCO formatting style](https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch/#coco-dataset-format).

I can even visualize the data using `Visualizer`:

```
for d in random.sample(train_data, 1):
    img = cv2.imread(d["file_name"])
    visualizer = Visualizer(img[:, :, :], scale=0.5)
    out = visualizer.draw_dataset_dict(d)
    plt.imshow(out.get_image()[:,:,::-1])
```

which gives me the expected output:
![image](https://user-images.githubusercontent.com/20720363/108342347-ff010c00-71da-11eb-8bad-19594fba9193.png)

Creating the trainer is also possible using `trainer = DefaultTrainer(cfg) `, but calling `trainer.train()` gives me a stack trace for the `AttributeError: Cannot find field 'gt_masks' in the given Instances!'` in DataLoader.
I am very confused about the error, because 'segmentation' is present in the train_data and the specified polygons are also valid telling from the output of `Visualizer`.

Anyway, thank you very much for your great work @hpanwar08 !

**Comment by hpanwar08** [comment]
Things seems fine to me. Is the error random or it occurs at the start of the training?

**Comment by mbuet2ner** [comment]
Actually, the first time I call `trainer.train()` I get an `AttributeError: Cannot find field 'gt_masks' in the given Instances!`, only the second time the `KeyError: 'segmentation'` occurs.

**Comment by mbuet2ner** [comment]
Telling from [this issue](https://github.com/facebookresearch/detectron2/issues/485) from the main detectron2 repo, this should only occur without masks. But the masks should be present, since `Visualizer` can get them?!

**Comment by mbuet2ner** [comment]
After a lot of debugging I found that for a couple of files the `segmentation` was missing somehow and therefore something went wrong during labeling.

As a somewhat ugly workaround I just replaced the empty segmentation with their respective bounding box.
Thanks for your help @hpanwar08 !

**Comment by hpanwar08** [comment]
Glad you figured it out.

**Comment by 14790897** [comment]
Thank you for your solution
