### ISSUE TITLE
Text Appearing with Table/Figures

### ISSUE THREAD

**Issue by deeptigoyal** [hpanwar08/detectron2#46]
Hello,

In PDF documents am currently working on text is coming along with tables and figures. I am only concerned with tables and figures (each one essential). Is there any parameter that I could set to avoid appearance of text?
Thanks

**Comment by Atul997** [comment]
Not sure about PDFs but you can check  predicted labels by creating a mapping dictionary like 
```
CATEGORIES2LABELS = {
    0: "text",
    1: "table",
    2: "figure",
    3: "title"
}
```
to map the predicted class and avoid text.

**Comment by deeptigoyal** [comment]
Thanks Atul for responding. I am mapping the labels but there are a few tables which has a portion of text even though the mapped label/name is coming as table. I guess re-training would only help.

**Comment by Atul997** [comment]
Check  tweaking threshold and  IOU and NMS.

**Comment by deeptigoyal** [comment]
Thanks Atul.
