### ISSUE TITLE
Labels not displaying while visualization of Results

### ISSUE THREAD

**Issue by GildedKnight** [hpanwar08/detectron2#5]
How to do we display labels with detectron2 on the output?

I checked the visualizer.py file, the logic seems to be fine within. But then again there are no labels displayed on the results, although the confidence score is displayed.
It uses the labels from the training dataset which is not available. But while training, the labels must have been encoded or dumped somewhere, can someone please point to the dump of the labels. Or if there is a way around to display the labels.

**Comment by rishabhshah13** [comment]
Did anyone get the solution to this?

**Comment by GildedKnight** [comment]
I got a solution, added labels manually in class visualizer.py file under
the variable "class_name"

**Comment by hpanwar08** [comment]
You can try this in your code.
```
MetadataCatalog.get("dla_val").thing_classes = ['text', 'title', 'list', 'table', 'figure']
```

**Comment by GildedKnight** [comment]
Thank you already did that
