### ISSUE TITLE
How to finetune this model?

### ISSUE THREAD

**Issue by gabrielcustodio** [hpanwar08/detectron2#7]
Can I use your custom class model to finetune for object detection or segmentation?
Basically, I should for register Detectron2 dataset?

**Comment by hpanwar08** [comment]
Yes you can use it for finetuning on your dataset. Follow the similar process to register as mentioned in tools/train_net_dla.py

**Comment by gabrielcustodio** [comment]
> Yes you can use it for finetuning on your dataset. Follow the similar process to register as mentioned in tools/train_net_dla.py. Update the config files according to your need.

Ok, thanks!
