### ISSUE TITLE
Historical Newspaper Segmentation

### ISSUE THREAD

**Issue by julianlanger** [hpanwar08/detectron2#8]
Hi,

I would like to use this implementation to segment historical newspaper pages. Should I simply use the existing model for prediction, or train the model further with additional historical newspaper ground truth? 

All the best

Julian

**Comment by hpanwar08** [comment]
You can try a couple of predictions on your data and see how the performance is. If it is not satisfactory then you need to finetune with your data.
Note that current models cannot detect header and footer as the PubLayNet dataset has no annotation for headers and footers.
